[package]
name = "mullvad-daemon"
version = "2019.10.0"
authors = [
    "Mullvad VPN",
    "Andrej Mihajlov <and@mullvad.net>",
    "Emīls Piņķis <emils@mullvad.net>",
    "Erik Larkö <erik@mullvad.net>",
    "Janito Vaqueiro Ferreira Filho <janito@mullvad.net>",
    "Linus Färnstrand <linus@mullvad.net>",
]
description = "Mullvad VPN daemon. Runs and controls the VPN tunnels"
license = "GPL-3.0"
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.25"
err-derive = "0.2.1"
fern = { version = "0.5", features = ["colored"] }
futures = "0.1"
ipnetwork = "0.15"
jsonrpc-client-core = "0.5"
jsonrpc-core = { git = "https://github.com/mullvad/jsonrpc", branch = "mullvad-fork" }
jsonrpc-ipc-server = { git = "https://github.com/mullvad/jsonrpc", branch = "mullvad-fork" }
jsonrpc-macros = { git = "https://github.com/mullvad/jsonrpc", branch = "mullvad-fork" }
jsonrpc-pubsub = { git = "https://github.com/mullvad/jsonrpc", branch = "mullvad-fork" }
lazy_static = "1.0"
log = "0.4"
log-panics = "2.0.0"
parking_lot = "0.9"
rand = "0.7"
regex = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio-core = "0.1"
tokio-retry = "0.2"
tokio-timer = "0.1"
uuid = { version = "0.7", features = ["v4"] }

mullvad-ipc-client = { path = "../mullvad-ipc-client" }
mullvad-paths = { path = "../mullvad-paths" }
mullvad-types = { path = "../mullvad-types" }
mullvad-rpc = { path = "../mullvad-rpc" }
talpid-core = { path = "../talpid-core" }
talpid-ipc = { path = "../talpid-ipc" }
talpid-types = { path = "../talpid-types" }

[target.'cfg(target_os="android")'.dependencies]
android_logger = "0.8"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
simple-signal = "1.1"

[target.'cfg(windows)'.dependencies]
ctrlc = "3.0"
windows-service = { git = "https://github.com/mullvad/windows-service-rs.git", rev = "1d5f9cc65658429414f2d62e4581e5a3e2532b99" }
winapi = { version = "0.3", features = ["errhandlingapi", "handleapi", "libloaderapi", "ntlsa", "synchapi", "tlhelp32", "winbase", "winerror", "winuser"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
winapi = "0.3"

[package.metadata.winres]
ProductName = "Mullvad VPN"
CompanyName = "Amagicom AB"
LegalCopyright = "(c) 2020 Amagicom AB"
InternalName = "mullvad-daemon"
OriginalFilename = "mullvad-daemon.exe"
